djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('student.urls')),
    path('', include('teacher.urls')),
    path('', include('userextend.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('course.urls')),
]

home/urls.py
from django.urls import path
from home import views


urlpatterns = [
    path('page/', views.homepage, name='page'),
    path('all_students/', views.home, name='list_of_students'),
    path('all_cars/', views.brands, name='list_of_cars'),
    path('', views.HomeTemplateView.as_view(), name='homepage')
]

student/models.py
from django.db import models

from course.models import Course
from teacher.models import Teacher


class Student(models.Model):
    gender_choices = (
        ('Male', 'Male'),
        ('Female', 'Female')
    )

    first_name = models.CharField(max_length=30, null=True)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField()
    date_of_birth = models.DateField()
    olympic = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    gender = models.CharField(max_length=10, choices=gender_choices)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

teacher/models.py
from django.db import models


class Teacher(models.Model):
    spec_choices = (
        ('Primary School', 'Primary School'),
        ('Middle School', 'Middle School'),
        ('High School', 'High School')
    )
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    specialisation = models.CharField(max_length=30, choices=spec_choices)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name} - {self.specialisation}'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Django Project</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Students
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if perms.student.add_student %}
                                <li><a class="dropdown-item" href="{% url 'create-student' %}">Create a new student</a>
                                </li>
                            {% endif %}
                            {% if perms.student.view_list_of_students %}
                                <li><a class="dropdown-item" href="{% url 'list-of-students' %}">List of students</a>
                                </li>
                            {% endif %}
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Teachers
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if perms.teacher.add_teacher %}
                                <li><a class="dropdown-item" href="{% url 'create-teacher' %}">Create a new teacher</a>
                                </li>
                            {% endif %}
                            {% if perms.teacher.view_teacher %}
                                <li><a class="dropdown-item" href="{% url 'list-of-teachers' %}">List of teachers</a>
                                </li>
                            {% endif %}
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            List of teachers
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for teacher in teachers %}
                                <li><a class="dropdown-item" href="{% url 'students-per-teacher' teacher.id %}">
                                    {{ teacher.first_name }} {{ teacher.last_name }}</a>
                                <li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            List of courses
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for course in courses %}
                                <li><a class="dropdown-item" href="{% url 'teacher-per-courses' course.teacher_id %}">
                                    {{ course.name }}</a>
                                <li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}"
                   class="btn btn-danger">Logout, {{ request.user.first_name }} {{ request.user.last_name }}</a>
            {% else %}
                <a href="{% url 'create-user' %}" class="btn btn-warning">Sign up</a>
                <a href="{% url 'login' %}" class="btn btn-dark">Login</a>
            {% endif %}
        </div>
    </div>
</nav>
<div class="container-fluid">
    {% block content %}
    {% endblock %}
</div>
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
</html>